name: Compilar Tracker App

on:
  workflow_dispatch: # Ejecutar y construir pulsando el botón en GitHub

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_apk:
    name: Construir APK de Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4
        
      - name: Configurar Java (Necesario para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # Versión estable más reciente
          channel: 'stable'

      - name: Generar Archivos de Plataforma
        working-directory: ./frontend
        run: flutter create --platforms android .

      - name: Cambiar el nombre nativo y añadir Permisos
        working-directory: ./frontend
        run: |
          sed -i 's/android:label=".*"/android:label="Rastreador de Juegos"/' android/app/src/main/AndroidManifest.xml
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET" />' android/app/src/main/AndroidManifest.xml

      - name: Configurar Iconos Oficiales Victor Engineer (Android)
        working-directory: ./frontend
        run: |
          if [ -d "assets/launcher_icons/android" ]; then
            cp -r assets/launcher_icons/android/* android/app/src/main/res/
            echo "✅ Iconos Victor Engineer instalados en mipmap de Android"
          fi

      - name: Configurar Firma Criptográfica Permanente (Keystore)
        run: |
          mkdir -p ~/.android
          cp frontend/assets/keystore/release.keystore ~/.android/debug.keystore
          echo "✅ Keystore de firma permanente configurado en ~/.android/debug.keystore"

      - name: Restaurar dependencias
        working-directory: ./frontend
        run: flutter pub get

      - name: Extraer Versión de pubspec.yaml
        id: app_version
        working-directory: ./frontend
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | cut -d '+' -f 1 | tr -d ' ')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Versión detectada para APK: $VERSION"

      - name: Compilar APK (Fat APK)
        working-directory: ./frontend
        run: flutter build apk --release --build-name=${{ steps.app_version.outputs.VERSION }} --build-number=${{ github.run_number }}

      - name: Subir APK al Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrackerApp_Android_APK
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
